/// Flutter icons SFDSMSIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SFDSMSIcons
///      fonts:
///       - asset: fonts/SFDSMSIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SFDSMSIcons {
  SFDSMSIcons._();

  static const _kFontFam = 'SFDSMSIcons';
  static const _kFontPkg = null;

  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data_center = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData student = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teacher = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
